# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dQdknj5mwSdciy15MFTAEpsTI3i9Tw0Y
"""

a=10
print(a)